import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { type ReactElement } from 'react';
import Header from './_components/Header';
import Provider from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <Provider>
      <html lang="ja">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </Provider>
  );
}
