name: ESLint & Prettier & Vitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: setup environments
        run: echo "${{ secrets.ENVIRONMENTS }}" > .env.test.local

      - name: Run ESLint
        run: yarn lint:ci
      - name: Run Prettier
        run: yarn format:ci
      - name: Run Vitest
        run: yarn test:ci
